services:
  macd-monitor:
    build: .
    # image: gnuhhung317/macd-monitor-dashboard
    container_name: macd-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    - /app/venv
    - /app/__pycache__
    - /app/ml/__pycache__
    - ./data:/app/data
    environment:
      # Timezone
      - TZ=Asia/Ho_Chi_Minh
      # Python environment
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - macd-network

networks:
  macd-network:
    driver: bridge
