import os, sys
import pandas as pd
from pathlib import Path

BASE_DIR = Path(r"d:\Code\Projects\self-projects\macd-overlay - Copy")
sys.path.append(str(BASE_DIR))
sys.path.insert(0, str(BASE_DIR / 'sniper_bot'))

from sniper_bot.sniper_scanner import SniperScanner
class MockDataProcessor:
    def __init__(self, symbols):
        self.current_time = None
        self.data = {}
        for s in symbols + ['BTCUSDT']:
            # All bitget parquets are named SYMBOLUSDT_USDT.parquet
            pq_path = BASE_DIR / "bitget-data" / "ohlcv" / f"{s}_USDT.parquet"
            if pq_path.exists():
                try:
                    df = pd.read_parquet(pq_path)
                    df['timestamp'] = pd.to_datetime(df['timestamp']).dt.tz_localize(None)
                    self.data[s] = df.sort_values('timestamp')
                except Exception as e:
                    print(f"⚠️ Error loading {s}: {e}")

    def get_historical_data(self, symbol, timeframe, since, until):
        if symbol not in self.data: return pd.DataFrame()
        df = self.data[symbol]
        open_candle_ts = self.current_time.floor('h')
        sliced = df[df['timestamp'] <= open_candle_ts].copy()
        if timeframe == '1d':
            sliced = sliced.set_index('timestamp').resample('1D').agg(
                {'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last', 'volume': 'sum'}
            ).dropna().reset_index()
        return sliced.tail(300)

def simulate_trades():
    import glob
    
    # Load all coins currently synced in bitget-data/ohlcv
    ohlcv_files = glob.glob(str(BASE_DIR / "bitget-data/ohlcv/*_USDT.parquet"))
    # Files are SYMBOL_USDT.parquet, e.g. ETHUSDT_USDT.parquet
    # We want symbol to be 'ETHUSDT'
    symbols = [Path(f).stem.replace('_USDT', '') for f in ohlcv_files]
    symbols = [s for s in symbols if s != 'BTCUSDT']
    
    start_dt = pd.Timestamp("2026-03-15 01:00:00")
    end_dt = pd.Timestamp("2026-03-22 00:00:00")
    
    print(f"🚀 Preloading local Parquet data for {len(symbols)} test symbols...")
    processor = MockDataProcessor(symbols)
    
    current = start_dt
    print(f"⏳ Stepping through Live Engine Simulation hour by hour (from {start_dt.date()} to {end_dt.date()})...")
    
    sys_stdout = sys.stdout
    scanner = SniperScanner(data_processor=processor)
    
    signals_found = 0
    total_hours = len(pd.date_range(start_dt, end_dt, freq='h'))
    hour_count = 0
    
    while current <= end_dt:
        processor.current_time = current
        hour_count += 1
        
        # Periodic progress heartbeat
        if hour_count % 12 == 1:
            progress = (hour_count / total_hours) * 100
            print(f"🔄 [Simulation] Progress: {progress:.1f}% ({hour_count}/{total_hours}h) | Current: {current.strftime('%Y-%m-%d %H:%M')}")

        # Suppress internal scanner prints (they get too spammy with 500 coins)
        sys.stdout = open(os.devnull, 'w')
        try:
            signals = scanner.scan(symbols, '1h')
        finally:
            sys.stdout = sys_stdout
        
        for sig in signals:
            signals_found += 1
            print(f"🔥 [{current.strftime('%Y-%m-%d %H:%M')}] LIVE ENGINE TRIGGERED: {sig['symbol']} {sig['type']} (Conf: {sig.get('confidence', 0):.4f})")
            
        current += pd.Timedelta(hours=1)
        
    print(f"✅ Simulation complete! Total exact signals generated by live engine across evaluated timeframe: {signals_found}")

if __name__ == '__main__':
    simulate_trades()
